<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Quote Generated</title>
</head>
<body>
<div class="container py-3">
    <h2 class="mb-5">Congratulations! You've been accepted to apply for car insurance with us.</h2>
    <h2 class="mb-3">Your quote is:</h2>
    <h1 class="mb-5">
        <?= "£" . number_format($quoteValue, 2); ?>
    </h1>
    <h2 class="mb-4">Would you like to accept this quote?</h2>
    <form class="mb-2" method="post" action="/quoteAccepted">
        <button type="submit" class="btn btn-primary">What a bargain, sign me up!</button>
    </form>
    <form method="post" action="/quoteRejected">
        <button type="submit" class="btn btn-outline-primary">No thank you</button>
    </form>
</div>
</body>
</html>



