<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>GabrielInsuranceExpert</title>
</head>
<body>
<div class="container p-3">
    <h1 class="mb-5 mt-2">Welcome to Car-insurance-expert.com!</h1>
    <h2 class="mb-3">Apply for Car Insurance</h2>
    <form method="post" action="/generateQuotePage">
        <div class="form-group mb-3">
            <label for="customerName">Please enter your name:</label>
            <input type="text" class="form-control" id="customerName" placeholder="Enter your name here"
                   name="customerName">
        </div>
        <div class="form-group mb-3">
            <label for="carType">What type of car do you have?</label>
            <select class="form-control" id="carType" name="carType">
                <?= \CarInsurance\ViewHelpers\CarTypeViewHelper::generateCarTypeDropdown($carTypes); ?>
            </select>
        </div>
        <div class="form-group mb-3">
            <label for="carValue">How much is your car worth?</label>
            <input type="number" class="form-control" id="carValue" name="carValue">
        </div>
        <div class="form-group mb-3">
            <label for="coverType">What type of cover are you looking for?</label>
            <select class="form-control" id="coverType" name="coverType">
                <?= \CarInsurance\ViewHelpers\CoverTypeViewHelper::generateCoverTypeDropdown($coverTypes); ?>
            </select>
            <button type="submit" class="btn btn-info mt-3">Submit</button>
        </div>
    </form>
</div>

</body>
</html>