<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Quote Accepted</title>
</head>
<body class="bg-light">
<div class="container pt-5 px-3 pb-3 bg-white">
    <h1 class="mb-4"><?= $customer_name ?>, your quote has been confirmed!</h1>
    <h4 class="mb-4">Your vehicle has now been ensured and you can drive with peace of mind &#128524</h4>
    <button class="btn btn-outline-success" type="button"><a class="text-decoration-none text-success" href="/">Get
            another quote</a></button>
</div>
</body>
</html>

